---
namespace: telekom_mms
name: acme
version: 4.2.0
readme: README.md
authors:
  - Sebastian Gumprich <sebastian.gumprich@telekom.de>
  - Andreas Hering <andreas.hering@telekom.de>
description: >-
  This collection contains a role for issuing ssl certificates via the ACME protocol. By default Let's Encrypt certificates are issued but it is also possible to use other certificate authorities which implement the ACME protocol.
license:
  - GPL-2.0-or-later
license_file: ""
tags:
  - acme
  - certificates
  - letsencrypt
  - security
  - ssl
dependencies:
  community.crypto: ">=1.0.0"
  openstack.cloud: ">=1.2.1"
  amazon.aws: ">=5.0.0"
  azure.azcollection: ">=1.14.0"
  community.general: ">10.3.0"
repository: https://github.com/telekom-mms/ansible-collection-acme
documentation: https://github.com/telekom-mms/ansible-collection-acme
homepage: https://github.com/telekom-mms/ansible-collection-acme
issues: https://github.com/telekom-mms/ansible-collection-acme/issues
build_ignore:
  - .ansible-lint
  - .gitattributes
  - .github
  - .yamllint.cfg
  - tests
