---
### include/role 3 - validate challenge
- name: Validate challenge only if it is created or changed # noqa no-handler
  when: acme_challenge is changed
  block:
    - name: Add a new TXT record to the SAN domains
      ansible.builtin.uri:
        url: http://localhost:8055/set-txt
        method: POST
        body_format: json
        # the dot after the hostname is required
        # crtl-f "Note that a period character is required at the end of the host name here." here:
        # https://github.com/letsencrypt/pebble/blob/master/cmd/pebble-challtestsrv/README.md
        body:
          {
            "host": "_acme-challenge.{{ item }}.",
            "value": "{{ acme_challenge_data[item]['dns-01']['resource_value'] }}"
          }
      loop: "{{ acme_domain.subject_alt_name }}"
      when:
        - acme_domain.subject_alt_name is defined
        # only runs if the challenge is run the first time, because then there is challenge_data
        - acme_challenge_data[item] is defined

    - name: Let the challenge be validated and retrieve the cert and intermediate certificate
      timeout: "{{ acme_challenge_timeout }}"
      community.crypto.acme_certificate:
        account_key_src: "{{ acme_account_key_path }}"
        account_email: "{{ acme_account_email }}"
        csr: "{{ acme_csr_path }}"
        cert: "{{ acme_cert_path }}"
        fullchain: "{{ acme_fullchain_path }}"
        chain: "{{ acme_intermediate_path }}"
        challenge: dns-01
        force: "{{ acme_force_renewal | default(false) }}"
        acme_directory: "{{ acme_directory }}"
        acme_version: 2
        terms_agreed: true
        remaining_days: "{{ acme_remaining_days }}"
        data: "{{ acme_challenge }}"
        validate_certs: "{{ acme_validate_certs | default(true) }}"
