- name: create the certificate for example.com
  hosts: localhost
  roles:
    - letsencrypt
  vars:
    domain:
      certificate_name: "example.com"
      common_name: "www.example.com"
      zone: "example.com"
      email_address: "ssl-admin@example.com"
      subject_alt_name:
        - example.com
    letsencrypt_create_private_keys: true
    letsencrypt_do_http_challenge: true
    letsencrypt_do_dns_challenge: false
    letsencrypt_use_acme_live_directory: false
    account_email: "ssl-admin@example.com"
    private_key_content: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          ....
    letsencrypt_s3_bucket_name: "example-ssl-bucket"
    letsencrypt_s3_config_access_key: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              ...
    letsencrypt_s3_config_secret_key: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              ...
