---
name: Codespell - Spellcheck

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codespell:
    uses: "telekom-mms/.github/.github/workflows/codespell.yml@e53c839b9c1d48d3bf7044182acf07aa32de00c3" # main
